### PR TITLE
docs: generate vscode snippets

### PR DESCRIPTION
**Pull request by hyoban**
### Additional context

I'm not sure if the format of the command follows specific rules. So I only generate for the full command name and @ alias

### CODE REVIEW

**Comment by antfu** [comment]
I am not sure if typing `epc` would be easier than `///` 😅

**Comment by hyoban** [comment]
Oh, yes. I agree with this. I will modify it later.

**Comment by antfu** [comment]
In that sense - do we still need the snippet? I guess with command shorthand they are already short enough to type

**Comment by hyoban** [comment]
OK, closing this PR for now. Since I don’t like abbreviations very much, it’s nice to be able to autocomplete the commands.

**Pull request closed without merging**
